### ISSUE TITLE
alguien con experiencia cómo organizador de meetup.com?

### ISSUE THREAD

**Issue by a0viedo** [banodejs/miembros#11]
quisiera requerir el email para que la gente se una al grupo de meetup, pero no tengo idea cómo sería la forma ortodoxa.
alguien se maneja? tal vez @alfathenus?

**Comment by andreslozadamosto** [comment]
buenas @a0viedo no entendi la pregunta. Queres invitar a gente para q se una al meetup desde la pag de meetup?

**Comment by a0viedo** [comment]
nosotros tenemos el grupo de meetup. ahora si exporto los miembros, lo que me genera no tiene emails. lo que en general nos piden los sponsors que ofrecen el lugar es lista de nombre,apellido y email. entonces cómo hacemos para pedirles el email a los miembros? cuando se registran a un evento? si se lo pedimos cuando se unen al grupo sería por única vez

**Comment by vichali** [comment]
Hola @a0viedo, en alguna oportunidad, intenté algo parecido y meetup argumentó que era imposible por razones de "seguridad"?

**Comment by jkutianski** [comment]
Raro que te pidan email. Lo que generalmente piden es DNI

Meetup nunca te pasa el email.

De: Alejandro Oviedo
Enviado el: ‎lunes‎, ‎30‎ de ‎marzo‎ de ‎2015 ‎03‎:‎45‎ ‎p.m.
Para: banodejs/miembros

nosotros tenemos el grupo de meetup. ahora si exporto los miembros, lo que me genera no tiene emails. lo que en general nos piden los sponsors que ofrecen el lugar es lista de nombre,apellido y email. entonces cómo hacemos para pedirles el email a los miembros? cuando se registran a un evento? si se lo pedimos cuando se unen al grupo sería por única vez

**Comment by bevacqua** [comment]
Yo me opondría a darle los mails de los participantes a los sponsors, imo

**Comment by a0viedo** [comment]
@bevacqua incluso a los que ponen venue? es raro ir a un lugar dónde no te pidan email

**Comment by bevacqua** [comment]
Por una cuestión de privacidad, etc. Para un attendee básicamente estás vendiendo sus datos, es una bomba de tiempo..

Personalmente no me importa pero intentaría evitarlo ya que no está muy bien visto

**Comment by a0viedo** [comment]
@bevacqua eso está más que claro. de enterarnos que un sponsor (previo) use los datos para spam, cortamos el vínculo con ese sponsor de una. bueno voy a ver si se puede charlar con wayra sobre futuras ocasiones

**Comment by jkutianski** [comment]
@a0viedo no es una buena solución entregar los emails, o cualquier otra información personal. Si alguien no te quiere dar esa información ¿que haces? ¿lo sacas del grupo? El DNI, Nombre y apellido son datos públicos, y tiene sentido pedirlos para pasárselos a la empresa que pone el lugar físico por razones de seguridad. El email es claramente para hacer spam.

**Comment by eafelix** [comment]
Eso seguro.

**Comment by jaclar** [comment]
Yo propongo que lo hacemos una planilla y la gente que esta interesado de recibir información del sponsor se puede inscribir. Así es opt-in y la gente sabe para que se usa su mail.
Que piensan?

**Comment by bevacqua** [comment]
+1

**Comment by sbaglieri** [comment]
la de la planilla la usan en varios eventos, no me parece mal.

**Comment by gabmontes** [comment]
Otra opción es mostrar los contactos de los sponsors en banners y antes y después de cada charla, de forma tal que el que quiera más info, que los contacte. Eso me parece más attendee+privacy-friendly todavía.

**Comment by jkutianski** [comment]
+1

De: Lars Jacob
Enviado el: ‎miércoles‎, ‎01‎ de ‎abril‎ de ‎2015 ‎12‎:‎16‎ ‎p.m.
Para: banodejs/miembros
CC: Juan Pablo Kutianski

Yo propongo que lo hacemos una planilla y la gente que esta interesado de recibir información del sponsor se puede inscribir. Así es opt-in y la gente sabe para que se usa su mail.
Que piensan?

**Comment by pepoviola** [comment]
+1

El 1 de abril de 2015, 14:37, Juan Pablo Kutianski <notifications@github.com
