### ISSUE TITLE
Workshops: si o no?

### ISSUE THREAD

**Issue by a0viedo** [banodejs/miembros#13]
Me gustaría escuchar opiniones sobre si creen que sería positivo cambiar el formato de algún meetup para hacer un esquema de workshop.

Los que ya podemos dar y se me vienen a la cabeza son:
- Sistemas distribuídos: bases de datos
- Profiling de CPU y memoria
- Post-mortem analisys of node processes

Si tienen otros para proponer/sugerir serán bienvenidos.

**Comment by zayrus** [comment]
Me parece que seria buenisimo que algún meetup sea un workshop! genial la idea!

**Comment by pr0duc3r** [comment]
Voto por SI a los workshops

En cuanto a profiling se podría complementar con una charla de clustering.muy a futuro

**Comment by gabmontes** [comment]
A mi también me parece muy buena la propuesta de hacer algún meetup distinto, tipo taller.

@a0viedo habría que hacer un nuevo repo que se llame "workshops"? Me gusta más la idea de que todas las reuniones, sean charlas, talleres o lo que se nos ocurra, esté como issues en un solo lugar.

**Comment by andreslozadamosto** [comment]
+1

**Comment by durancristhian** [comment]
Yo estoy a favor de hacer un workshop. Cambiar la didáctica del evento de vez en cuando yo creo que nos da muchas ventajas entre las cuales destaco que "conozcamos más el nivel de nuestra comunidad", porque claro está que no todos estamos al mismo nivel. Hacer un workshop también implica (considero yo) que sepamos bien que vamos a hacer y como nos vamos a dividir, porque tenemos que poder darle algo útil a alguien con experiencia y alguien con no tanta experiencia, distinto al formato tradicional de charla. Esto lo digo porque para hacer un workshop, definitivamente tenemos que saber con quienes vamos a contar para armar el contenido y no esperar que la gente se amolde a algo que tengamos armado, aunque insisto, es lo que puedo aportar ahora.

Hacer un workshop creo que demandar un poquito más de esfuerzo, pero eso nos gusta.

En lo que pueda ayudar, ahi estaré

**Comment by andreslozadamosto** [comment]
Concuerdo con @durancristhian 
Tal vez, como una primer experiencia, se puede hacer un hackaton donde a partir de las librerias opensource q tenga la gente del grupo, codear y ayudarles a corregir bugs, crear test, refactoring, etc. Posiblemente eso requiera un poco menos de esfuerzo.

**Comment by adrixvoid** [comment]
Definitivamente si!, estaría buenísimo también en algún momento hacer algún mini proyecto, algo que sirva y que permita que tengamos algo tangible, algo reutilizable. Por ejemplo, hacer una pequeña app y que de ahí vayamos viendo que cosas poder ir agregando. Lo que faltaría también es hablar un poco sobre las puestas en producción, cómo se suben a un hosting, el famoso deploy.

**Comment by eafelix** [comment]
+1

**Comment by jkutianski** [comment]
+1

**Comment by lmokto** [comment]
claro que si! y mas si es de Sistemas distribuídos, Profiling o cosas asi

**Comment by rojasa19** [comment]
+1

**Comment by AquiGorka** [comment]
+1

**Comment by jkutianski** [comment]
+1

**Comment by vichali** [comment]
+1

**Comment by sbaglieri** [comment]
+1

**Comment by AlanVerbner** [comment]
+1

**Comment by npessolani** [comment]
+1 y podria andar algo de la nueva domotica de Node en Arduino o la libreria Johnny Five

**Comment by gpalli** [comment]
+1 a los workshops en particular para poder encontrar memory leaks o tema performance, creo que estan relacionados ambos temas. Gracias.

**Comment by mikealche** [comment]
+1 a los workshops y a eso que dijo @adrxlm de construir entre todos explicando los procesos una app  funcional y util! A mi en lo personal me encantaría ver y participar de la construccion de zero a production de una SaaS por ejemplo. Creo que sería super educativo analizar todas las partes del proceso.

**Comment by vichali** [comment]
+1 y +buena la de @miguelalche

**Comment by sergiolepore** [comment]
+1 (no estoy en BA, pero me gusta la propuesta. Espero vivirla algún día)

**Comment by a0viedo** [comment]
@sergiolepore pero podemos hacerlo en Córdoba, no? @ivancevich pone el auto :P

**Comment by ivancevich** [comment]
@a0viedo seeeeh :smile:

**Comment by eafelix** [comment]
yo pongo la coca-cola y los sandwiches de ida , llevo agua para los que quieran (?)

**Comment by diegosanchez** [comment]
:+1: a los workshops. Una alternativa para workshop podría ver de hacer algún aporte a algún proyecto open source basado en Node.  Leyendo código de gente más experimentada se aprende mucho

**Comment by eafelix** [comment]
Me gusta la idea de un workshop de análisis de algún framework conocido. buena idea @diegosanchez

**Comment by figui** [comment]
+1

**Comment by sergiolepore** [comment]
"BA Node.js: edición especial Córdoba". Sale, de una (?)

**Comment by eafelix** [comment]
muy buena @sergiolepore !
Tenemos que coordinar y hacerlo. 
@a0viedo @mgtitimoli

**Comment by mgtitimoli** [comment]
@sergiolepore consegui lugar y vamos!

**Comment by sergiolepore** [comment]
Summoning @avilaton (organizador de nodeschool-cba).

**Comment by avilaton** [comment]
Gracias @sergiolepore por materializarme.

Lugar hay, hicimos una pruebita de nodeschool hace unas semanas en el CREA Fab Lab, un laboratorio de fabricación digital que además de poner el lugar, tiene impresoras 3d, cortadora laser y algunos bichitos para conectar a johnny-five y joder. 

Lo más dificil es la coordinacion del día. Lo hicimos un sábado, de 10 a 17, y todos quedamos medios quemados. Al mediodía cortamos para unos choris en la terraza. Quienes de BA se prenderían? Tienen que coincidir.

En cuanto a los temas, muchos quizá estén motivados por cuestiones super avanzadas, pero los attendees no. La idea de como sacar desde cero un SaaS me suena mejor.

**Comment by andreslozadamosto** [comment]
+1

**Comment by mgtitimoli** [comment]
@sergiolepore @avilaton queremos ir para alla, cuando vamos, les parece un finde de Noviembre? Quieren hacer unas charlas, todo un dia de NodeSchool, ambas? Tenemos muchas ganas de ir, esto podria ser un encuentro de muchos a lo largo de todo el pais, asi que:
- Finde 7-8/11
- FInde 14-15/11
- FInde 21-22/11
- Finde 28-29/11

Que dia les queda mejor?

**Comment by marcemira** [comment]
+1 suena copado, puedo ayudar con la organización.
