### ISSUE TITLE
Miembro

### ISSUE THREAD

**Issue by sfabrizio** [banodejs/miembros#19]
Holaaa!! 

Ya estoy llendo a las meetups, estoy en slack.. creo que me falta ser miembro acá y hacer algún que otro aporte. 

Saludos.

**Comment by nicolasdanelon** [comment]
Lamebotas

**Comment by sfabrizio** [comment]
jajaja tenes razon viejaaa.. creo que cierro el issue, hagamos un projecto nosotros. Sabes codear? o solo PHP? jajaja

**Comment by nicolasdanelon** [comment]
3030313130303130203030313030303030203031313030303131203031313031313131203031313130303131203031313030303031203031313130303131203030313131303130203030313030303030203031313031313030203031313030313031203031313030313130203031313130313030203030313031313031203031313130303030203031313030303031203031313030313030203030313031313030203030313030303030203031313030313031203031313130303131203031313030303131203031313130303130203031313031303031203031313030303130203031313031303031203031313130303131203031313130313030203031313030313031203030313030303030203031313031313031203031313030303031203031313031313030203030313030303030203031313130303030203031313130303130203031313031313131203031313131303031203031313030313031203031313030303131203031313130313030203031313031313131203030313030303030203031313030303031203031313030303130203031313130303130203031313030303031203031313131303130203031313031313131203030313030303031

**Comment by a0viedo** [comment]
hecho!

**Comment by sfabrizio** [comment]
Gracieee!

**Comment by sfabrizio** [comment]
6a 61 6a 61 6a 61 20 62 75 65 6e 61 20 68 61 63 6b 65 72 72 72 21 21 20 45 6c 69 6f 74 20 75 6e 20 70 6f 72 6f 74 6f 2e 2e 20

**Comment by a0viedo** [comment]
@sfabrizio btw creo que por default no se muestra en tu perfil, lo tenes que ir a cambiar en https://github.com/orgs/banodejs/people

**Comment by gabmontes** [comment]
@nicolasdanelon podrías mandar un PR para corregir esos dos typos que viste!

**Comment by gabmontes** [comment]
@nicolasdanelon 3031303030303031203031313130313031203031313031313130203031313130303031203031313130313031203031313030313031203030313030303030203031313030313030203031313030313031203031313030303130203031313030313031203031313130303130203131303030303131203130313031313031203031313030303031203030313030303030203031313031303030203031313030303031203031313030303130203031313030313031203031313130303130203030313030303030203031313130303130203031313030313031203031313130303131203031313130303030203031313031313131203031313031313130203031313030313030203031313031303031203031313030313030203031313031313131203030313030303030203031313030313031203031313031313130203030313030303030203031313030313031203031313031313030203030313030303030203031313031313031203031313031303031203031313130303131203031313031313031203031313031313131203030313030303030203031313030303131203131303030303131203130313130303131203031313030313030203031313031303031203031313030313131203031313031313131203030313031313130203030313031313130203030313031313130203030313030303030203031313031303130203031313030303031203030313030303031

**Comment by nicolasdanelon** [comment]
3031313031313130203031313030303031203031313031303030203030313031313030203030313030303030203031313031313130203031313031313131203030313030303030203031313130313030203031313030313031203030313030303030203031313130303030203031313130303130203031313030313031203031313031313131203031313030303131203031313130313031203031313130303030203031313030313031203031313130303131203030313031313130203030313030303030203031313031313030203031313031313131203030313030303030203031313030313031203031313130303131203031313130313030203031313030303031203031313030303130203031313030303031203030313030303030203031313030313131203031313030303031203031313130303131203031313130313030203031313030303031203031313031313130203031313030313030203031313031313131203030313030303030203031313030303031203030313030303030203031313030313130203031313030303031203031313030303130203031313130303130203031313031303031203031313131303130203031313031303031203031313031313131203030313031313030203030313030303030203031313030313031203031313031313030203030313030303030203031313030313031203031313130303130203031313130303130203031313031313131203031313130303130203030313030303030203031313030313031203031313130303131203031313130313030203031313030303031203031313030303130203031313030303031203030313030303030203031313130303131203031313031313131203031313031313030203031313031313131203030313030303030203031313030313031203031313031313130203030313030303030203031313030313031203031313130303131203031313130313030203031313030313031203030313030303030203031313031303031203031313130303131203031313130303131203031313130313031203031313030313031203030313030303030203030313131303131203030313031303031

**Comment by gabmontes** [comment]
3031303031303130203031313030303031203030313030303031203030313030303030203031303031313131203031313031303131203030313030303031
